import { Book } from '@book-library/shared';

export const books: Book[] = [
  {
    title: `JavaScript: The Definitive Guide: Master the World's Most-Used Programming Language`,
    authors: ['David Flanagan'],
    isbn: 9781491952023,
    edition: 7,
    length: 704,
    totalCount: 20,
    availableCount: 3,
  },
  {
    title: `Python Crash Course, 3rd Edition: A Hands-On, Project-Based Introduction to Programming`,
    authors: ['Eric Matthes'],
    isbn: 9781718502703,
    edition: 3,
    length: 552,
    totalCount: 15,
    availableCount: 12,
  },
  {
    title: `Linux Bible`,
    authors: ['Christopher Negus'],
    isbn: 9781119578888,
    edition: 10,
    length: 928,
    totalCount: 18,
    availableCount: 5,
  },
  {
    title: `C Programming Language`,
    authors: ['Dennis M. Ritchie', 'Brian W. Kernighan'],
    isbn: 9780131103627,
    edition: 2,
    length: 272,
    totalCount: 30,
    availableCount: 27,
  },
  {
    title: `Computer Architecture: A Quantitative Approach`,
    authors: ['John L. Hennessy', 'David A. Patterson'],
    isbn: 9780128119051,
    edition: 6,
    length: 936,
    totalCount: 8,
    availableCount: 7,
  },
  {
    title: `Computer Networking: A Top-Down Approach`,
    authors: ['James Kurose', 'Keith Ross'],
    isbn: 9780133594140,
    edition: 7,
    length: 864,
    totalCount: 10,
    availableCount: 3,
  },
  {
    title: `Learning PHP, MySQL & JavaScript: A Step-by-Step Guide to Creating Dynamic Websites (Learning PHP, MYSQL, Javascript, CSS & HTML5)`,
    authors: ['Robin Nixon'],
    isbn: 9781492093824,
    edition: 6,
    length: 823,
    totalCount: 12,
    availableCount: 12,
  },
  {
    title: `Docker: Up & Running: Shipping Reliable Containers in Production `,
    authors: ['Sean Kane', 'Karl Matthias'],
    isbn: 9781098131821,
    edition: 3,
    length: 422,
    totalCount: 6,
    availableCount: 0,
  },
  {
    title: `Pro Git`,
    authors: ['Scott Chacon', 'Ben Straub'],
    isbn: 9781484200773,
    edition: 2,
    length: 521,
    totalCount: 14,
    availableCount: 5,
  },
];
