import { Book } from '@book-library/shared';

export const books: Book[] = [
  {
    title: `JavaScript: The Definitive Guide: Master the World's Most-Used Programming Language`,
    authors: ['David Flanagan'],
    isbn: 9781491952023,
    edition: 7,
    length: 704,
    totalCount: 20,
    availableCount: 3,
    coverExtension: 'jpg',
  },
  {
    title: `Python Crash Course, 3rd Edition: A Hands-On, Project-Based Introduction to Programming`,
    authors: ['Eric Matthes'],
    isbn: 9781718502703,
    edition: 3,
    length: 552,
    totalCount: 15,
    availableCount: 12,
    coverExtension: 'jpg',
  },
  {
    title: `Linux Bible`,
    authors: ['Christopher Negus'],
    isbn: 9781119578888,
    edition: 10,
    length: 928,
    totalCount: 18,
    availableCount: 5,
    coverExtension: 'jpg',
  },
  {
    title: `C Programming Language`,
    authors: ['Dennis M. Ritchie', 'Brian W. Kernighan'],
    isbn: 9780131103627,
    edition: 2,
    length: 272,
    totalCount: 30,
    availableCount: 27,
    coverExtension: 'jpg',
  },
  {
    title: `Computer Architecture: A Quantitative Approach`,
    authors: ['John L. Hennessy', 'David A. Patterson'],
    isbn: 9780128119051,
    edition: 6,
    length: 936,
    totalCount: 8,
    availableCount: 7,
    coverExtension: 'jpg',
  },
  {
    title: `Computer Networking: A Top-Down Approach`,
    authors: ['James Kurose', 'Keith Ross'],
    isbn: 9780133594140,
    edition: 7,
    length: 864,
    totalCount: 10,
    availableCount: 3,
    coverExtension: 'jpg',
  },
  {
    title: `Learning PHP, MySQL & JavaScript: A Step-by-Step Guide to Creating Dynamic Websites (Learning PHP, MYSQL, Javascript, CSS & HTML5)`,
    authors: ['Robin Nixon'],
    isbn: 9781492093824,
    edition: 6,
    length: 823,
    totalCount: 12,
    availableCount: 12,
    coverExtension: 'jpg',
  },
  {
    title: `Docker: Up & Running: Shipping Reliable Containers in Production `,
    authors: ['Sean Kane', 'Karl Matthias'],
    isbn: 9781098131821,
    edition: 3,
    length: 422,
    totalCount: 6,
    availableCount: 0,
    coverExtension: 'jpg',
  },
  {
    title: `The Rust Programming Language, 2nd Edition`,
    authors: ['Steve Klabnik', 'Carol Nichols'],
    isbn: 9781718503106,
    edition: 2,
    length: 560,
    totalCount: 14,
    availableCount: 5,
    coverExtension: 'jpg',
  },
  {
    title: 'The Last Wish',
    authors: ['Andrzej Sapkowski'],
    isbn: 9788375780635,
    edition: 3,
    length: 332,
    totalCount: 10,
    availableCount: 3,
    coverExtension: 'jpg',
  },
  {
    title: 'Sword of Destiny',
    authors: ['Andrzej Sapkowski'],
    isbn: 9788375780642,
    edition: 3,
    length: 400,
    totalCount: 10,
    availableCount: 3,
    coverExtension: 'jpg',
  },
  {
    title: 'The Art of War',
    authors: ['Sun Tzu'],
    edition: 13,
    isbn: 9781454911869,
    length: 272,
    totalCount: 8,
    availableCount: 5,
    coverExtension: 'jpg',
  },
  {
    title:
      'Mythology (75th Anniversary Illustrated Edition): Timeless Tales of Gods and Heroes',
    authors: ['Edith Hamilton', 'Jim Tierney'],
    edition: 15,
    isbn: 9780316438520,
    length: 384,
    totalCount: 5,
    availableCount: 4,
    coverExtension: 'jpg',
  },
  {
    title: `The Fellowship of the Ring`,
    authors: ['J. R. R. Tolkien'],
    edition: 6,
    isbn: 9780358380238,
    length: 544,
    totalCount: 8,
    availableCount: 2,
    coverExtension: 'jpg',
  },
  {
    title: `The Two Towers`,
    authors: ['J. R. R. Tolkien'],
    edition: 6,
    isbn: 9780358380245,
    length: 448,
    totalCount: 8,
    availableCount: 2,
    coverExtension: 'jpg',
  },
  {
    title: `The Return of the King:`,
    authors: ['J. R. R. Tolkien'],
    edition: 6,
    isbn: 9780358380252,
    length: 544,
    totalCount: 8,
    availableCount: 2,
    coverExtension: 'jpg',
  },
];
