name: Integrate
on:
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - name: Lint
        run: pnpm lint
  format:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - uses: ./.github/actions/setup
      - name: Format
        run: pnpm lint
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: format
          branch: ${{ github.head_ref }}
